Repository TUM-Dev/NavigaTUM, pull requests merged in 2022-06, with the labels that each got.

#142 Maximize Map on Desktop
  webclient/src/modules/interactive-map.js
  webclient/src/views/view/view-view.scss
Labels: feature, frontend

#147 added more testcases for the search api
  server/test/test-queries.yaml
Labels: feature, server

#136 Add external links popup to OSM / Google Maps
  webclient/src/variables.scss
  webclient/src/views/view/i18n-view.yaml
  webclient/src/views/view/view-view.inc
  webclient/src/views/view/view-view.js
  webclient/src/views/view/view-view.scss
Labels: feature, frontend

#153 added an error mesage for users without js-execution
  webclient/src/i18n.yaml
  webclient/src/index.html
Labels: bug, frontend

#154 improved feedback description handling
  server/Cargo.toml
  server/src/feedback.rs
Labels: bug, server

#157 improved readability in darkmode for the footer
  webclient/src/main.scss
Labels: bug, frontend
