Repository TUM-Dev/NavigaTUM, pull requests merged in 2022-01, with the labels that each got.

#11 Add first readme
  README.md
  data/README.md
  data/search_synonyms.json
  deployment/deployment-README.md
  resources/webclient-screenshot-1.png
  resources/webclient-screenshot-2.png
  resources/webclient-screenshot-3.png
  server/README.md
  webclient/README.md
  webclient/config-local.js
  webclient/gulpfile.js
Labels: documentation

#12 Additional Documentation
  SECURITY.md
  webclient/gulpfile.js
  webclient/src/.well-known/gpc.json
  webclient/src/.well-known/robots.txt
  webclient/src/.well-known/security.txt
Labels: documentation, enhancement

#14 Add very simple search result page and add limit support in the API
  server/Cargo.toml
  server/README.md
  server/src/main.rs
  server/src/search.rs
  webclient/src/core.js
  webclient/src/i18n.yaml
  webclient/src/index.html
  webclient/src/modules/autocomplete.js
  webclient/src/variables.scss
  webclient/src/views/search/i18n-search.yaml
  webclient/src/views/search/view-search.inc
  webclient/src/views/search/view-search.js
  webclient/src/views/search/view-search.scss
Labels: enhancement, server, frontend

#15 Deployment todos
  server/README.md
  server/src/main.rs
  server/test/search_test.py
  webclient/config-local.js
  webclient/src/md/api.md
Labels: bug, deployment

#20 Improve information about sources
  data/compile.py
  data/data_format_geo-entry.yaml
  data/processors/patch.py
  data/processors/roomfinder.py
  data/processors/structure.py
  data/processors/tumonline.py
  webclient/src/views/view/i18n-view.yaml
  webclient/src/views/view/view-view.inc
  webclient/src/views/view/view-view.scss
Labels: frontend, data
